# Generated by Django 3.1.5 on 2021-01-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jahid', to='blog.learn')),
            ],
        ),
    ]
