# Generated by Django 3.1.5 on 2021-01-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_testlearn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlearn',
            name='learn',
        ),
        migrations.AddField(
            model_name='testlearn',
            name='learn',
            field=models.ManyToManyField(to='blog.Learn'),
        ),
    ]
