# Generated by Django 3.1.5 on 2021-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210113_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlearn',
            name='learn',
            field=models.ManyToManyField(related_name='test', to='blog.Learn'),
        ),
    ]
